### ISSUE TITLE
add support for Intelij IDEA 2020.3

### ISSUE THREAD

**Issue by jsbh05** [nhat-phan/merge-request-integration#115]

**Comment by artitrue** [comment]
Doesn't work with WebStorm 2020.3:
> 11:23	Plugin error: Plugin 'Merge Request Integration EE - Code Review for GitLab' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is WS-203.5981.135

**Comment by jmatthiesen81** [comment]
Every release the same procedure.

**Comment by krishnaku** [comment]
How long does it take to get this to work with new new releases? I am on PyCharm 2020.3 and the plugin is incompatible. 
This is a very useful plugin, and I realize how hard it is for a smaller shop/individual developer to keep up with this stuff. But I am paying for the plug-in with the expectation that there will be some expectation of reliability. I would even be willing to pay more than the nominal fee that you currently charge for the plug-in. 

This issue was raised 2 weeks ago, and at the very least a note from the developer saying when a fix might be expected would have been nice. It seems like it is broken across all 2020.3 releases of the platform and it is unreasonable to expect us to not upgrade the platform or not have a paid plug-in be broken indefinitely with each upgrade. 

Please, at least give a status update on when this may be fixed - otherwise I am giving up on this..

**Comment by drewoko** [comment]
Same here. Paying each month for that plugin and because of that, I cannot update Intellij to the latest version. I think I need to fork that and just make a version for myself....

**Comment by petromir** [comment]
+1
When a new version is expected?

**Comment by mjhamiltonus** [comment]
Also looking for 2020.3 support - needed specifically for CLion.  Not sure if doing the IDEA version will fix, but, probably.

Also paying license (through company - opinions expressed do not necessarily reflect those of my employer etc. etc.)

Thanks for the great plugin!  Works great.

**Comment by pchelk1n** [comment]
We will not renew subscription

**Comment by mjhamiltonus** [comment]
> We will not renew subscription

I care less about the subscription price than the tool!  I really like it! Does this mean you do not intend to support it moving forward?

**Comment by jmatthiesen81** [comment]
+1

**Comment by nhat-phan** [comment]
Thank you for letting me know. 

I adapted the plugin to support latest IDE version. I'll release new version with some bugs fixed within this week (hopefully with a draft-comments feature)

**Comment by krishnaku** [comment]
Thank you! This is a really useful plug-in. Your work is much
appreciated. I would happily pay more if you raised your price, or
sponsor on Gihub if you have that set up. I know it’s not easy to be a
maintainer..


Krishna

On January 6, 2021, "Paweł Fus" <notifications@github.com> wrote:

> Thank you for letting me know.
>
> I adapted the plugin to support latest IDE version. I'll release new

> version with some bugs fixed within this week (hopefully with a draft-

> comments feature)
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nhat-phan/merge-request-
integration/issues/115#issuecomment-755585897>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAFX2W34Q3MQN2WCZ6O4T43SYS4ZNANCNFSM4UJMHTFQ>.
