### ISSUE TITLE
Feture Request: Allow saving filters

### ISSUE THREAD

**Issue by riclucio** [nhat-phan/merge-request-integration#31]
It would be good to allow saving filters to merge requests for quickly pick, like "My open reviews", "Reviews assigned to me", etc.
Today every time I need to apply the filter to see all my open reviews and those pending my approval.
Also in the "Author", "Assignee" and "Approver" filter fields dropdown, there could be a "\<My Self\>" or just "me" option that points to the current user, so I don't need to type it.

**Comment by riclucio** [comment]
To be clear, I'm speaking about these filters:
![image](https://user-images.githubusercontent.com/48838923/74280970-58974680-4cfc-11ea-9044-99b2f0ca22b7.png)

**Comment by nhat-phan** [comment]
My idea is you can see the most important things in the Home tab, that's why it's not closable. 

I'll keep the filter as it is but will introduce the way to add a new tab in Home screen (of course with custom filter). What do you think?

<img width="698" alt="Screen Shot 2020-02-13 at 20 15 44" src="https://user-images.githubusercontent.com/34987391/74469811-a39c8f80-4e9d-11ea-9611-dcc4fd483367.png">

**Comment by riclucio** [comment]
Something I'm considering is that, today when I open the config in this screen:
![image](https://user-images.githubusercontent.com/48838923/74490755-5540be00-4ea8-11ea-94ff-d3d6d0e90b07.png)
If I my project has hundreds of merge requests (including those I'm not directly involved), it will fetch them all upfront, as no filters are applied on initial load, which maybe slow.
My suggestion is that I can somehow define a filter that runs by default on this screen that will only bring relevant merge requests for me (which should be a small subset of the overall merge requests of the project).
Does it make sense?

**Comment by nhat-phan** [comment]
You meant keep the state of filters so you don't have to choose them again after opening the tab, right?

**Comment by riclucio** [comment]
Yep
