### ISSUE TITLE
Add comment to specific position of source code not working.

### ISSUE THREAD

**Issue by Savak** [nhat-phan/merge-request-integration#4]
First, thank you for your job, your plugin is great :)

I was doing a code review and wanted to add a comment to a specific line. I enjoyed when i saw that the functionnality exist. But when I clicked on the button "Create", nothing happened. I tried by unchecking the "Add comment to the following position of source code" and here, that's worked fine.

**Comment by Savak** [comment]
@smallcreep, can you explain how you get this stack trace please ? I try to check out my idea.log file but I didn't find anything about this error.

**Comment by nhat-phan** [comment]
@Savak Thank you for reporting. It's really tricky to add a comment in a specific position. Depends on the kind of change (deleted, replaced, inserted) gitlab requires different kind of params such as: old_line, new_line, old_path, new_path. That's why I display ugly option text fields to modify them in add comment area. Could you please try to fill the line if nothing happens after click "Create".

To improve this part, I'll show a message in case there is any error, hope it helps (it will be release in next version [v2019.2.3](https://github.com/nhat-phan/merge-request-integration/projects/1))

@smallcreep Seems the stacktrace is problem when IDE doesn't support markdown. I create [the issue](https://github.com/nhat-phan/merge-request-integration/issues/5) to fix it separately. Thank you for letting me know.

**Comment by Savak** [comment]
@nhat-phan I already try to fill all text box, keep it empty, etc. But nothing happen.

**Comment by SToto98** [comment]
Same problem here with phpstorm 2019.3.1, plugin 2019.3.2 and GitLab CE 12.4.3. 
Tell me if you want more infos and thank you for your work. We will take a licence for 11 people as soon as the plugin works for us :)

**Comment by nhat-phan** [comment]
Could you guys please provide information like:

- What kind of change you want leave a comment (deleted, inserted, updated or normal line)
- How many commits has been selected. If you review some commits of MR, the Code review will displayed text: "Code Review xx/yy commits", if you review all commits the button is "Code Review"

Also could you please don't fill any text fields because it supposed to be filled automatically when you select "Add Comment" in context menu, then click Create Comment and see what will happen.

Thanks a lot!

**Comment by nhat-phan** [comment]
@Savak @smallcreep @SToto98 The updates is available (v2019.3.3), could you guys please give it another try. Thank you!

Links:

- [Community Edition](https://plugins.jetbrains.com/plugin/13607-merge-request-integration-ce--code-review-for-gitlab)
- [Enterprise Edition](https://plugins.jetbrains.com/plugin/13615-merge-request-integration-ee--code-review-for-gitlab/)

**Comment by Savak** [comment]
Tested and approved. Thanks a lot @nhat-phan !
