### ISSUE TITLE
Feature: Jump to file from comment

### ISSUE THREAD

**Issue by panther-hq** [nhat-phan/merge-request-integration#58]
Hey,

Is it possible to create an option to move to a file from a comment?

![image](https://user-images.githubusercontent.com/8721698/80344852-85bdb480-8868-11ea-9151-d4c182446929.png)

I see it in such a way that the right button shows the options and there is the move to file option

**Comment by nhat-phan** [comment]
Yes, the [feature](https://plugins.jetbrains.com/plugin/13615-merge-request-integration-ee--code-review-for-gitlab/features) is available since version `2020.1.5` 

If you cannot update it automatically, you can go to plugin pages ([CE](https://plugins.jetbrains.com/plugin/13607-merge-request-integration-ce--code-review-for-gitlab) or [EE edition](https://plugins.jetbrains.com/plugin/13615-merge-request-integration-ee--code-review-for-gitlab)) and download it manually.

<img width="960" alt="Screen Shot 2020-04-24 at 10 43 29" src="https://user-images.githubusercontent.com/34987391/80349489-9de50200-886f-11ea-9697-8cf693a47429.png">
